### ISSUE TITLE
Conduit bump from 0.12.5 to 0.12.8 lost module name in reporting

### ISSUE THREAD

**Issue by coladarci** [conduitframework/conduit_appsignal#1]
Let's say we have a Poison error in one of our subscribers. Instead of being told which, all of a sudden we started just seeing `__MODULE__.process` as the name:

<img width="362" alt="screen shot 2018-11-16 at 4 12 44 pm" src="https://user-images.githubusercontent.com/1004167/48653489-7b806100-e9ba-11e8-8e28-9ec1e43b309c.png">

This happened w/ the jump from 12.5 to 12.8. Any ideas?

We are including the plug like this:

`plug(ConduitAppsignal.Plug.Subscriber, subscriber: __MODULE__)`

Thanks!

**Comment by blatyo** [comment]
Can you try out master and see if that fixes it?

`init` for a plug now receives the AST of the options passed to the plug. It was a change that was necessary to support functions in options.

**Comment by coladarci** [comment]
BOOM! I can confirm master works correctly w/ Appsignal!

**Comment by blatyo** [comment]
Thanks, you can use v0.6.2 now.
